[dependencies]

# Core libraries
packaging = "*" 
torch = "*"
icecream = "*"
absl-py = "*"
accelerate = "*"
aiohttp = "*"
aiosignal = "*"
prompt_toolkit = "*"
annotated-types = "*"
anyio = "*"
async-timeout = "*"
attrs = "*"
Brotli = "*"
certifi = "*"
cffi = "*"
chardet = "*"
charset-normalizer = "*"
click = "*"
colorama = "*"
cryptography = "*"
DataProperty = "*"
datasets = "*"
dill = "*"
distro = "*"
einops = "*"
evaluate = "*"
fast-hadamard-transform = "*"
filelock = "*"
flash-attn = "*"
frozenlist = "*"
fsspec = "*"
glog = "*"
gmpy2 = "*"
h11 = "*"
httpcore = "*"
httpx = "*"
huggingface-hub = "*"
idna = "*"
Jinja2 = "*"
joblib = "*"
jsonlines = "*"
lm-eval = "*"
MarkupSafe = "*"
mbstrdecoder = "*"
mkl-fft = "*"
mkl-random = "*"
mkl-service = "*"
mpmath = "*"
multidict = "*"
multiprocess = "*"
networkx = "*"
ninja = "*"
nltk = "*"
numexpr = "*"
numpy = "*"
openai = "*"
pandas = "*"
pathvalidate = "*"
peft = "*"
Pillow = "*"
portalocker = "*"
primefac = "*"
protobuf = "*"
psutil = "*"
pyarrow = "*"
pybind11 = "*"
pycountry = "*"
pycparser = "*"
pydantic = "*"
pydantic_core = "*"
pyOpenSSL = "*"
PySocks = "*"
pytablewriter = "*"
python-dateutil = "*"
python-gflags = "*"
pytz = "*"
PyYAML = "*"
# quiptools-cuda = "*"
regex = "*"
requests = "*"
responses = "*"
rouge-score = "*"
sacrebleu = "*"
safetensors = "*"
scikit-learn = "*"
scipy = "*"
sentencepiece = "*"
six = "*"
sniffio = "*"
sqlitedict = "*"
sympy = "*"
tabledata = "*"
tcolorpy = "*"
threadpoolctl = "*"
tokenizers = "*"
tqdm = "*"
tqdm-multiprocess = "*"
transformers = "*"
triton = "*"
typepy = "*"
typing_extensions = "*"
tzdata = "*"
urllib3 = "*"
xxhash = "*"
yarl = "*"
zstandard = "*"

[dev-dependencies]
# Add any development-only dependencies here
